# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Zali
  de: Zali
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  de: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  de: de.html
feed:
  en: /feed.xml
  de: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://za-li.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: "/:categories/:title"